Repository batoulapps/adhan-js, pull requests merged in 2022-04, with the labels that each got.

#96 refactor: format files using prettier
  .eslintrc.js
  .husky/pre-commit
  .prettierignore
  .prettierrc
  Adhan.d.ts
  Adhan.js
  Adhan.js.map
  commitlint.config.js
  jest.config.js
  package-lock.json
  package.json
  src/Adhan.js
  src/Astronomical.js
  src/CalculationMethod.js
  src/CalculationParameters.js
  src/Coordinates.js
  src/DateUtils.js
  src/HighLatitudeRule.js
  src/Madhab.js
  src/MathUtils.js
  src/PolarCircleResolution.js
  src/Prayer.js
  src/PrayerTimes.js
  src/Qibla.js
  src/Rounding.js
  src/Shafaq.js
  src/SolarCoordinates.js
  src/SolarTime.js
  src/SunnahTimes.js
  src/TimeComponents.js
  test/adhan.test.js
  test/astronomical.test.js
  test/dist.test.js
  test/math.test.js
  test/qibla.test.js
  test/sunnah.test.js
  test/times.test.js
  webpack.config.js
Labels: enhancement

#103 Remove unused dependencies
  package-lock.json
  package.json
Labels: dependencies

#102 Fix example
  example.html
Labels: bug

#104 Update workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .releaserc.json
  package-lock.json
  package.json
Labels: enhancement
